"""Six editable, deterministic explanatory diagrams for the EAGLE article.

Source figures: extract_speculative_paper_figures.py and the adjacent sources.json.
These diagrams summarize mechanisms, not measured durations or speedups.
Training recipes follow the SpecForge snapshot linked in the article.
"""
from __future__ import annotations

import argparse
from html import escape
from pathlib import Path

W = 1120
FONT = "Inter, Microsoft YaHei, Noto Sans CJK SC, Arial, sans-serif"
INK, MUTED, LINE = "#172033", "#637083", "#CAD3E1"
COLORS = {
    "neutral": ("#F3F5F8", LINE),
    "target": ("#E8F0FF", "#2F6FE4"),
    "draft": ("#E2F5F1", "#138A7E"),
    "seq": ("#EEE9FF", "#7656D8"),
    "anchor": ("#FFF2D6", "#B47815"),
    "accept": ("#E4F4EA", "#2E8B57"),
    "reject": ("#FDE9E7", "#C05252"),
}
XS = [32, 304, 576, 848]


class Figure:
    def __init__(self, title, desc, height):
        self.height = height
        self.parts = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{height}" viewBox="0 0 {W} {height}" role="img" aria-labelledby="title desc">',
                      f'<title id="title">{escape(title)}</title><desc id="desc">{escape(desc)}</desc>',
                      f'<style>text{{font-family:{FONT};fill:{INK}}}</style>',
                      f'<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5L0 10Z" fill="{INK}"/></marker></defs>',
                      f'<rect width="{W}" height="{height}" fill="white"/>']
        self.text(32, 39, title, 26, weight=700)

    def text(self, x, y, text, size=20, color=INK, anchor="start", weight=400):
        self.parts.append(f'<text x="{x}" y="{y}" font-size="{size}" style="fill:{color}" text-anchor="{anchor}" font-weight="{weight}">{escape(text)}</text>')

    def rect(self, x, y, w, h, kind="neutral", dashed=False, radius=10):
        fill, stroke = COLORS[kind]
        dash = ' stroke-dasharray="5 5"' if dashed else ""
        self.parts.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{radius}" fill="{fill}" stroke="{stroke}" stroke-width="1.5"{dash}/>')

    def box(self, x, y, title, lines=(), kind="neutral", w=240, h=112):
        self.rect(x, y, w, h, kind)
        self.text(x + w / 2, y + 32, title, 22, anchor="middle", weight=650)
        for i, line in enumerate(lines):
            self.text(x + w / 2, y + 62 + 25 * i, line, 19, anchor="middle")

    def arrow(self, *points, dashed=False):
        d = "M" + " L".join(f"{x},{y}" for x, y in points)
        dash = ' stroke-dasharray="5 5"' if dashed else ""
        self.parts.append(f'<path d="{d}" fill="none" stroke="{INK}" stroke-width="1.6" stroke-linejoin="round" marker-end="url(#arrow)"{dash}/>')

    def chain(self, y, xs=XS, width=240):
        for left, right in zip(xs, xs[1:]):
            self.arrow((left + width, y), (right - 5, y))

    def tokens(self, x, y, labels, kinds=None, size=44, gap=10):
        for i, label in enumerate(labels):
            k = kinds[i] if kinds else "neutral"
            self.rect(x + i * (size + gap), y, size, 40, k, radius=6)
            self.text(x + i * (size + gap) + size / 2, y + 27, label, 20, anchor="middle", weight=600)

    def note(self, y, text):
        self.text(32, y, text, 19, MUTED)

    def finish(self):
        return "\n".join(self.parts + ["</svg>\n"])


def dflash_training():
    f = Figure("DFlash 训练：用严格可见的 target context 预测整块", "冻结 target 提供上下文；随机 anchor 后全部 mask；位置加权 CE 更新 draft，anchor 自身不计入预测损失。", 520)
    f.chain(142, xs=XS[:3])
    f.box(32, 86, "完整训练序列", ["prompt + response", "真实 token 与 loss mask"], "neutral")
    f.box(304, 86, "Target forward", ["参数冻结", "提取多层 hidden"], "target")
    f.box(576, 86, "每块可见 context", ["只保留位置 < anchor", "投影到各 draft 层 K/V"], "target")
    # Labels are gathered from the original data, not generated by context KV.
    f.box(848, 86, "真实后续 token", ["标签 E F G H", "来自训练序列"], "neutral")
    f.arrow((152, 198), (152, 265))
    f.arrow((696, 198), (696, 265))
    f.arrow((968, 198), (968, 265))
    f.chain(328)
    f.box(32, 272, "随机选择 anchor", ["例如选中 D", "保留原序列 position ID"], "anchor")
    f.box(304, 272, "构造 masked block", ["D  M  M  M  M", "M = MASK，块间隔离"], "anchor")
    f.box(576, 272, "一次 draft forward", ["同块双向 attention", "冻结 LM head → logits"], "draft")
    f.box(848, 272, "位置加权 CE", ["只监督后 4 个位置", "前部出错的权重更高"], "seq")
    f.note(436, "反向更新 draft backbone 与条件投影；冻结 embedding / LM head 仍传递对 draft 的梯度。")
    f.note(472, "论文默认 full attention；同一块可互看 MASK 表示，但不能偷看 anchor 及其后的 target hidden。")
    return f


def dflash_inference():
    f = Figure("DFlash 推理：整块并行提出，target 一次验证", "例子中 target 已处理 ABC，anchor D 尚未 forward；draft 提出 EFGH；接受 EF，拒绝 G，产生新 anchor G*。", 480)
    f.text(32, 85, "轮初状态", 20, weight=650)
    f.tokens(152, 57, ["A", "B", "C"], ["target"] * 3)
    f.text(330, 85, "已有 target hidden / KV", 19)
    f.tokens(646, 57, ["D"], ["anchor"])
    f.text(709, 85, "anchor 已确定，尚未送入 target", 19)
    f.chain(211)
    f.box(32, 150, "准备输入", ["D  M  M  M  M", "历史 context KV 已就绪"], "anchor", h=122)
    f.box(304, 150, "并行 draft", ["backbone + LM head", "一次提出 E F G H"], "draft", h=122)
    f.box(576, 150, "并行 target verify", ["输入 D E F G H", "按前缀逐位接受 / 拒绝"], "target", h=122)
    f.box(848, 150, "提交与下一轮", ["保留已接受前缀", "写入有效 context KV"], "accept", h=122)
    f.text(32, 330, "验证示例", 20, weight=650)
    f.tokens(152, 301, ["E", "F", "G", "H"], ["accept", "accept", "reject", "neutral"])
    f.text(392, 330, "G 首次拒绝，H 不再接受", 19)
    f.arrow((652, 322), (700, 322))
    f.tokens(722, 301, ["E", "F", "G*"], ["accept", "accept", "anchor"])
    f.text(900, 330, "G* 为新 anchor", 19)
    f.note(399, "本轮只提交 D、E、F 对应的 target hidden；新采样的 G* 要到下轮才执行 forward。")
    f.note(435, "若整块全接受，则由最后一个 verify 位置再给出 bonus；随机验证使用实际 proposal q。")
    return f


def dspark_training():
    f = Figure("DSpark 训练：学候选分布，也学条件接受率", "SpecForge 使用真实前驱修正 logits，CE 与分布 L1 训练 q，分布重叠的 detach 值监督 confidence；STS 另用留出数据校准。", 596)
    f.box(32, 83, "训练序列 + anchor", ["D 为 anchor", "真实后续 E F G H"], "neutral")
    f.box(304, 83, "冻结 target", ["多层 hidden → context", "末层 hidden → teacher p"], "target")
    f.arrow((272, 139), (299, 139))
    f.box(576, 83, "Teacher forcing", ["前驱 D E F G", "标签 E F G H"], "anchor")
    f.text(863, 117, "推理时前驱换成", 20)
    f.text(863, 148, "刚选出的 draft token", 20)
    f.arrow((152, 195), (152, 224))
    f.arrow((424, 195), (424, 224))
    f.arrow((696, 195), (696, 224))
    f.chain(286)
    f.box(32, 230, "构造 block", ["D  M  M  M", "4 个 query → 4 个预测"], "anchor")
    f.box(304, 230, "并行 backbone", ["一次得到 h 与基础 U", "anchor 行也参与预测"], "draft")
    f.box(576, 230, "轻量序列头", ["Markov / RNN 修正", "使用真实前驱"], "seq")
    f.box(848, 230, "训练输出", ["修正后的分布 q", "confidence head 输出 c"], "seq")
    # Supervision is summarized under the forward pass; each card names its inputs.
    f.arrow((968, 342), (968, 370), (196, 370), (196, 399))
    f.arrow((560, 370), (560, 399))
    f.arrow((924, 370), (924, 399))
    f.box(32, 405, "Token CE", ["真实标签与 q", "监督生成内容"], "neutral", w=328, h=104)
    f.box(396, 405, "分布 L1", ["teacher p 与修正后的 q", "增大两者的概率重叠"], "target", w=328, h=104)
    f.box(760, 405, "Confidence BCE", ["目标 = detach(1 − TV(p,q))", "估计条件接受率"], "seq", w=328, h=104)
    f.note(552, "三项按配置加权训练；训练后另用留出数据做 STS 校准，再提供给验证长度调度器。")
    return f


def dspark_inference():
    from draw_dspark_execution import inference
    return inference(Figure)


def dspark_host_budget():
    from draw_dspark_execution import host_budget
    return host_budget(Figure)


def dflash2_training():
    f = Figure("DFlash 2 训练：同时改善候选覆盖与候选选择", "这是文章固定版本的 SpecForge 训练路径：DFlash token objective 加 strict top-K selector CE，不声称为作者 checkpoint 的完整配方。", 512)
    f.note(79, "SpecForge 公开 recipe：target 冻结；继承 DFlash 的 anchor、context mask 与 block 构造。")
    f.chain(186)
    f.box(32, 130, "Masked blocks", ["anchor + MASK", "严格可见 target context"], "anchor")
    f.box(304, 130, "带卷积的 backbone", ["局部 hidden 混合", "所有位置仍并行执行"], "draft")
    f.box(576, 130, "冻结 LM head", ["得到全词表 unary U", "提供各位置基础概率"], "neutral")
    f.box(848, 130, "Strict top-K", ["按 unary 分数取候选", "不补入漏召回的真值"], "seq")
    f.arrow((696, 242), (696, 280), (442, 280), (442, 319))
    f.arrow((968, 242), (968, 319))
    f.box(32, 325, "真实前驱 token", ["teacher forcing", "推理时换成已选前驱"], "anchor", w=240)
    f.box(304, 325, "主 token objective", ["在全词表上监督", "继续改善 backbone"], "draft", w=276)
    f.box(732, 325, "候选集上的 selector CE", ["真值在 top-K 中 → 计算损失", "真值缺席 → 跳过该位置"], "seq", w=356)
    f.arrow((152, 437), (152, 457), (910, 457), (910, 441))
    f.note(494, "两项可联合训练；selector_stop_gradient、warmup 与权重由配置决定，不是固定两阶段训练。")
    return f


def dflash2_inference():
    f = Figure("DFlash 2 推理：先并行打分，再走一条候选路径", "带卷积 backbone 一次生成 unary logits；邻接候选对并行评分；从 anchor 出发因果 walk，只有选出的一条链送入 target。", 630)
    f.chain(179)
    f.box(32, 123, "带卷积的 draft", ["一次 block forward", "hidden 局部混合也并行"], "draft")
    f.box(304, 123, "保留候选", ["每个位置 unary top-K", "候选集合已经确定"], "neutral")
    f.box(576, 123, "并行邻接评分", ["基础分数 + 前驱匹配", "不再执行 backbone"], "seq")
    f.box(848, 123, "因果 walk → verify", ["按已选前驱选下一词", "target 只验证一条链"], "target")
    f.text(32, 286, "候选示意", 20, weight=650)
    f.text(172, 286, "为便于阅读仅画 K=3、3 个位置；连线为已预计算的候选对，粗线为所选路径。", 18, MUTED)
    cx = [330, 536, 742]
    ys = [323, 383, 443]
    # Candidate-pair edges are behind node faces. Emphasize the causal path.
    for a, b in zip(cx, cx[1:]):
        for ya in ys:
            for yb in ys:
                f.parts.append(f'<path d="M{a+86},{ya+20} L{b},{yb+20}" stroke="{LINE}" stroke-width="1" fill="none"/>')
    f.tokens(82, 383, ["D"], ["anchor"], size=60)
    for yy in ys:
        f.parts.append(f'<path d="M142,403 L330,{yy+20}" stroke="{LINE}" stroke-width="1" fill="none"/>')
    for (x1,y1),(x2,y2) in [((142,403),(330,403)),((416,403),(536,343)),((622,343),(742,403))]:
        f.parts.append(f'<path d="M{x1},{y1} L{x2},{y2}" stroke="#7656D8" stroke-width="3.5" fill="none" marker-end="url(#arrow)"/>')
    for j, x in enumerate(cx):
        f.text(x+43, 315, f"位置 {j+1}", 18, anchor="middle")
        for k, y in enumerate(ys):
            selected = k == [1,0,1][j]
            f.tokens(x, y, [f"{['E','F','G'][j]}{k+1}"], ["seq" if selected else "neutral"], size=86)
    f.text(871, 362, "所选链", 20, weight=650)
    f.text(871, 399, "E2 → F1 → G2", 21)
    f.text(871, 435, "随链保存实际 q", 19)
    f.text(871, 471, "step 0 前驱 = anchor", 17)
    f.text(871, 497, "greedy：argmax，q=one-hot", 17)
    f.text(871, 523, "T>0：逆 CDF 采样，q = 行概率", 17)
    f.note(565, "这里是逐步 greedy / sampling walk，不是 Viterbi 全局最优路径，也不是 target 验证整张候选树。")
    f.note(601, "候选外 proposal q = 0；随机拒绝后的残差采样仍可输出 top-K 以外的 target token。")
    return f


FIGURES = {
    "dflash-training.svg": dflash_training,
    "dflash-inference.svg": dflash_inference,
    "dspark-training.svg": dspark_training,
    "dspark-inference.svg": dspark_inference,
    "dspark-host-budget.svg": dspark_host_budget,
    "dflash2-training.svg": dflash2_training,
    "dflash2-inference.svg": dflash2_inference,
}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", nargs="?", type=Path,
                        default=Path(__file__).resolve().parents[1] / "content/sglang/img/speculative-diffusion")
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    for name, draw in FIGURES.items():
        figure = draw()
        (args.output / name).write_text(figure.finish(), encoding="utf-8")
        print(f"{name}: {W} x {figure.height}")


if __name__ == "__main__":
    main()
